### ISSUE TITLE
[Question]have you tried to use blendshape on this network

### ISSUE THREAD

**Issue by JSHZT** [Doubiiu/CodeTalker#15]
Hello, have you tried to use blendshape on this network? I tried to train under the teachingforcing strategy, but I found that the inference was very problematic, but if I also use the teachingforcing similar guidance for inference, the result is very good . But it's pointless to reason like this,do you have any suggestions for this?

**Comment by Doubiiu** [comment]
Sorry I didn't try blendshape on this network. I guess it may need to tune hyper-parameters or alternate the network architecture to make it work.

**Comment by JSHZT** [comment]
Thank you for your reply. Now I am trying to train codetalker with blendshape data without using the teachingforcing strategy. I am still waiting for the experimental results. As mentioned in my previous question, this is relatively full. It takes nearly 5 days to train 100 epochs
