### ISSUE TITLE
Ture may misspelling？

### ISSUE THREAD

**Issue by youngstu** [Doubiiu/CodeTalker#16]
https://github.com/Doubiiu/CodeTalker/blob/3335dcdc86253892c480b4119b111a53e9ae886f/config/vocaset/stage1.yaml#L34
  sync_bn: Ture  # adopt sync_bn or not

Ture->True？

**Comment by Doubiiu** [comment]
Yes it is a typo. Thanks for pointing-out this. I think it will the pre-trained model should be correct and doesn't affected by this typo.
