### ISSUE TITLE
BIWI dataset has 536 vertices_npy and 532 wav?

### ISSUE THREAD

**Issue by youngstu** [Doubiiu/CodeTalker#20]
After BIWI processed, found BIWI dataset has 536 vertices_npy and 532 wav. Is the number of BIWI dataset right? Thx.

**Comment by Doubiiu** [comment]
I also encountered the data missing problem. But I think it is OK as you only need to make sure all the BIWI TestA and TestB train
/val/test data exist and complete.

**Comment by youngstu** [comment]
The acutal BIWI dataset for train, val, test is 190, 32, 24.
`Loaded data: Train-190, Val-24, Test-32`

But in paper, the BIWI dataset for train, val, test is 192, 32, 24.

**Comment by Doubiiu** [comment]
Yeap I just check it and it should be 190.
