### ISSUE TITLE
Why using teacher-forcing scheme?

### ISSUE THREAD

**Issue by youngstu** [Doubiiu/CodeTalker#21]
Why using teacher-forcing scheme? 
Teacher-forcing scheme proved to be worse than autoregressive scheme in many paper such as Faceformer and FaceXHuBERT?

**Comment by Doubiiu** [comment]
We use it due to the efficiency concern and find the performance is not bad. BTW, we have tried teacher-forcing training in FaceFormer and found the performance difference is quite limited.

**Comment by youngstu** [comment]
> We use it due to the efficiency concern and find the performance is not bad. BTW, we have tried teacher-forcing training in FaceFormer and found the performance difference is quite limited.

Got it, thanks.
