### ISSUE TITLE
Quantitative evaluation between CodeTalker and Faceformer is not align and conflicting.

### ISSUE THREAD

**Issue by youngstu** [Doubiiu/CodeTalker#22]
Quantitative evaluation between CodeTalker and Faceformer is not align and conflicting.

![Screenshot from 2023-04-25 16-35-35](https://user-images.githubusercontent.com/26452514/234221818-f40e4f2f-ea91-4c24-9621-0a805f64a296.png)
![Screenshot from 2023-04-25 16-35-24](https://user-images.githubusercontent.com/26452514/234221832-25a1d50d-6d31-4ec0-bd0a-c0670a934763.png)

**Comment by Doubiiu** [comment]
As FaceFormer did not release their metric calculation code and we select the lip vertices by ourselves, which may be distinct from those of FaceFormer.

**Comment by youngstu** [comment]
> As FaceFormer did not release their metric calculation code and we select the lip vertices by ourselves, which may be distinct from those of FaceFormer.

Got it, thanks.
