### ISSUE TITLE
ImportErorr

### ISSUE THREAD

**Issue by Lipolan** [Doubiiu/CodeTalker#33]
Hello, can you ask how to resolve this error? Thank you for your reply!
![47633f749ff1f139e0081681fa53bfa](https://github.com/Doubiiu/CodeTalker/assets/95124201/44503629-106b-4026-a947-e8f0e00f61b2)

**Comment by Doubiiu** [comment]
Hi, I haven't encountered this problem. If you are facing this problem during rendering, maybe this [issue](https://github.com/EvelynFan/FaceFormer/issues/67) can help.

**Comment by WellTung666** [comment]
> Hello, can you ask how to resolve this error? Thank you for your reply! ![47633f749ff1f139e0081681fa53bfa](https://user-images.githubusercontent.com/95124201/239229146-44503629-106b-4026-a947-e8f0e00f61b2.png)

'apt-get install -y python-opengl libosmesa6'  can resolve this error.
