### ISSUE TITLE
my result is not the same as the paper result. why?

### ISSUE THREAD

**Issue by zhengshi119** [Doubiiu/CodeTalker#36]
Frame Number: 3879
Lip Vertex Error: 1.8149e-03
FDD: 4.6162e-05

**Comment by Doubiiu** [comment]
Hi. I didn't come across that high LVE value in the experiments. If you train the model from scratch, the differences may come from:
(i): the preprocessed dataset (you can test by using the provided model)
(ii): You can test the intermediate models which may have a better balance between perceptual quality and quantitative performance.
The reasons are various, I am not sure about that.

**Comment by zhengshi119** [comment]
thank you！
