### ISSUE TITLE
how can I  implement mean and standard deviation?

### ISSUE THREAD

**Issue by zhengshi119** [Doubiiu/CodeTalker#38]
![image](https://github.com/Doubiiu/CodeTalker/assets/73488996/54a6126c-058d-4415-a5e8-8640c91f6977)

**Comment by Doubiiu** [comment]
Hi, as we described in Sec. 4.3 (the 2nd paragraph):
1. calculate the L2 distance of adjacent-frame facial motions
2. calculate the mean and std along the temporal axis for each vertex
