### ISSUE TITLE
how to download data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl?

### ISSUE THREAD

**Issue by WellTung666** [Doubiiu/CodeTalker#41]
I sign in 'https://voca.is.tue.mpg.de/' but no find these files, can you tell me how to downlaod?  thanks~

**Comment by Doubiiu** [comment]
Hi, after logging in, please click the "Download" button at the top of the webpage. Then scroll down to the bottom of the page, and you will see "Training Data (8 GB)" along with a "Download" button. Click to download and unzip the file, and then you will find the data you mentioned.

**Comment by WellTung666** [comment]
> Hi, after logging in, please click the "Download" button at the top of the webpage. Then scroll down to the bottom of the page, and you will see "Training Data (8 GB)" along with a "Download" button. Click to download and unzip the file, and then you will find the data you mentioned.


I have downloaded it, thanks~

**Comment by Doubiiu** [comment]
OK, then I will close this issue.
