### ISSUE TITLE
The lve.txt and fdd.txt files for VOCA were not found

### ISSUE THREAD

**Issue by liushengtong-nreal** [Doubiiu/CodeTalker#43]
Hello, when I was looking at the evaluation code, I only found some files for BIWI, such as the vertex index files lve.txt and fdd.txt. Can you provide these two files for the VOCA dataset? I would be very grateful if it was possible

**Comment by Doubiiu** [comment]
Hi, since the subjects in the test set of vocaset are all unseen during training, vocaset is not suitable for quantitative evaluation. Thus, we don't have lve.txt and fdd.txt for this dataset.
