### ISSUE TITLE
No vocabulary dataset found

### ISSUE THREAD

**Issue by drj-123456** [Doubiiu/CodeTalker#47]
No .pkl file（data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl） found from this URL：https://voca.is.tue.mpg.de/download.php

Could you tell me exactly where to find these files?

**Comment by Doubiiu** [comment]
See this [issue #41](https://github.com/Doubiiu/CodeTalker/issues/41).

**Comment by drj-123456** [comment]
Thanks!
