### ISSUE TITLE
Question about training error in stage 1

### ISSUE THREAD

**Issue by GIT-LZL629** [Doubiiu/CodeTalker#5]
Traceback (most recent call last):
  File "/media/E/3DTalk/CodeTalker-main/main/train_pred.py", line 242, in <module>
    main()
  File "/media/E/3DTalk/CodeTalker-main/main/train_pred.py", line 48, in main
    main_worker(args.train_gpu, args.ngpus_per_node, args)
  File "/media/E/3DTalk/CodeTalker-main/main/train_pred.py", line 109, in main_worker
    loss_train, motion_loss_train, reg_loss_train = train(train_loader, model, loss_fn, optimizer, epoch, cfg)
  File "/media/E/3DTalk/CodeTalker-main/main/train_pred.py", line 148, in train
    model.autoencoder.eval()
  File "/home/anaconda3/envs/3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'VQAutoEncoder' object has no attribute 'autoencoder'

Could you tell me where is the "autoencoder"?

**Comment by Doubiiu** [comment]
Hi. What is your training command and actual training code (.py)? It seems that you are training discrete motion prior (stage1) using the stage2 training script?

**Comment by GIT-LZL629** [comment]
Thanks for replying to me.

sh scripts/train.sh CodeTalker_s1 config/vocaset/stage1.yaml vocaset s1

**Comment by GIT-LZL629** [comment]
It works and appreciate it.

Could you tell me where I can find "facebook/wav2vec2-base-960h"?

**Comment by Doubiiu** [comment]
It is a pretrained moel weights of [wav2vec2](https://huggingface.co/facebook/wav2vec2-base-960h) released by facebook. If it cannot be automatically downloaded, you can download these files manually and change the path to your local `wav2vec2-base-960h` folder.

**Comment by MagicRedZero** [comment]
> 

if [ "${stage}" = "s1" ]; then

**Comment by sxyddo35831** [comment]
> 

Yes! I encountered the same error and solved it with this method
