### ISSUE TITLE
perplexity

### ISSUE THREAD

**Issue by drj-123456** [Doubiiu/CodeTalker#51]
During the training, the perplexity has been rising, what does the perplexity mean？

**Comment by Doubiiu** [comment]
Hi, perplexity is a metric to help you know the usage rate of the learned code. Higher perplexity means a higher usage rate.

**Comment by drj-123456** [comment]
Thank you for your answer. That is to say, during the training process, the perplexity has been rising, does it have no effect on the training results?

**Comment by Doubiiu** [comment]
I think it has no direct effect on the results, but intuitively, more activated code are welcomed, showing the full usage of the codebook.
