### ISSUE TITLE
What is the lip vertex range when calculating LVE?

### ISSUE THREAD

**Issue by kimhyungkyu-1208** [Doubiiu/CodeTalker#57]
When calculating LVE, how did you set the lip vertex range criteria in BIWI and VOCASET?
Can you tell me if there are any documents or methods you referenced?

**Comment by Doubiiu** [comment]
Hi, we only calculate LVE on BIWI following FaceFormer. For the lip vertex range selection, we tried to refer previous works by contacting the authors, as neither of them released code for calculating LVE, but we didn't get any accurate references on that. We think it is fair to select the lip vertex range with visualization software such as MeshLab and compare all the methods on it, without any tricky selection.

**Comment by kimhyungkyu-1208** [comment]
Thank you for your kind reply:)
Have a nice day

**Comment by Doubiiu** [comment]
Not a problem.
