### ISSUE TITLE
psbody module

### ISSUE THREAD

**Issue by Tinaa23** [Doubiiu/CodeTalker#60]
Hi. Thank you for sharing your code.
When trying to run the `demo.py` file, it returns  `No module named 'psbody'`.
I tried to install it with pip, but it returned `No matching distribution found for psbody`.
Can you help how to solve this?

**Comment by Doubiiu** [comment]
Hi, it should be installed via [https://github.com/MPI-IS/mesh](https://github.com/MPI-IS/mesh), as mentioned in the environment setup step.

**Comment by Tinaa23** [comment]
> Hi, it should be installed via https://github.com/MPI-IS/mesh, as mentioned in the environment setup step.

Thank you for your reply. After installing `MPI-IS/mesh` I received this error: `can not import name 'plyutils' from 'psbody.mesh.serialization'`. 
When I checked the `psbody/mesh/serialization` directory, there was no `plyutils.py` file. 
Can you help with this?

**Comment by Tinaa23** [comment]
> > Hi, it should be installed via https://github.com/MPI-IS/mesh, as mentioned in the environment setup step.
> 
> Thank you for your reply. After installing `MPI-IS/mesh` I received this error: `can not import name 'plyutils' from 'psbody.mesh.serialization'`. When I checked the `psbody/mesh/serialization` directory, there was no `plyutils.py` file. Can you help with this?

I solved this issue. The problem was with my installation path.
