### ISSUE TITLE
the parameters of TCN are fixed, so how to unfreeze

### ISSUE THREAD

**Issue by Shirley-0708** [Doubiiu/CodeTalker#61]
@Doubiiu You mentioned that during training, the parameters of TCN are fixed, whereas the other parts of the model are learnable. Where is the relevant code set for freezing? Can you point it out because I want to unfreeze and make TCN learnable，thanks a lot !

**Comment by Doubiiu** [comment]
Hi. Thanks for your interest! The corresponding code is L20(`self.audio_encoder.feature_extractor._freeze_parameters()`) in [stage2.py](https://github.com/Doubiiu/CodeTalker/blob/main/models/stage2.py). You may get more information about wav2vec2.0 from the [huggingface page / source code](https://huggingface.co/docs/transformers/model_doc/wav2vec2) or the [paper](https://arxiv.org/abs/2006.11477).

**Comment by Shirley-0708** [comment]
Thanks for your prompt reply! I have commented out this line `self.audio_encoder.feature_extractor._freeze_parameters()` and hope it works.
