### ISSUE TITLE
a part of biwi data is missing？ 

### ISSUE THREAD

**Issue by yangan200203** [Doubiiu/CodeTalker#63]
When I preprocess the data ,I get this

Not found: BIWI_Process/data/F1/vert/e20/
Not found: BIWI_Process/data/F3/vert/e02/
Not found: BIWI_Process/data/F3/vert/e03/
Not found: BIWI_Process/data/M1/vert/e01/
Not found: BIWI_Process/data/M1/vert/e02/
Not found: BIWI_Process/data/M1/vert/e03/
Not found: BIWI_Process/data/M1/vert/e04/
Not found: BIWI_Process/data/M1/vert/e05/
Not found: BIWI_Process/data/M1/vert/e06/
Not found: BIWI_Process/data/M1/vert/e07/
Not found: BIWI_Process/data/M1/vert/e08/
Not found: BIWI_Process/data/M1/vert/e09/
Not found: BIWI_Process/data/M1/vert/e10/
Not found: BIWI_Process/data/M1/vert/e11/
Not found: BIWI_Process/data/M1/vert/e12/
Not found: BIWI_Process/data/M1/vert/e13/
Not found: BIWI_Process/data/M1/vert/e14/
Not found: BIWI_Process/data/M1/vert/e15/
Not found: BIWI_Process/data/M1/vert/e16/
Not found: BIWI_Process/data/M1/vert/e17/
Not found: BIWI_Process/data/M1/vert/e18/
Not found: BIWI_Process/data/M1/vert/e19/
Not found: BIWI_Process/data/M1/vert/e20/
Not found: BIWI_Process/data/M2/vert/e20/

It's normal?

**Comment by Doubiiu** [comment]
yeap it is normal for me, as the original data may be incomplete. The missing data is neither within the training set nor the testing set, so there should be no problem.

**Comment by yangan200203** [comment]
Thanks a lot
