### ISSUE TITLE
How to get the lve.txt and fdd.txt files

### ISSUE THREAD

**Issue by Shirley-0708** [Doubiiu/CodeTalker#64]
Hi, I was wondering how to get the lve.txt and fdd.txt, could you give more details? Thanks a lot!

**Comment by Doubiiu** [comment]
Hi you mean those files in `BIWI/regions/` right? Actually we use [blender](https://www.blender.org/) to interactively select those regions (vertices) and then export them.

**Comment by Tankaishen** [comment]
> Hi you mean those files in `BIWI/regions/` right? Actually we use [blender](https://www.blender.org/) to interactively select those regions (vertices) and then export them.

What file do you import into blender? The templates.pkl or other file. I find blender doesn't take the .pkl file as input. How to convert recommended? Thanks

**Comment by Doubiiu** [comment]
Hi. You can also use .ply files (BIWI.ply and FLAME_sample.ply).

**Comment by hrWong** [comment]
Hi @Doubiiu Thanks for your work, I would like to know how I should export to get data like lve.txt
