### ISSUE TITLE
关于在vocaset上训练meshtalk问题

### ISSUE THREAD

**Issue by AlongLove** [Doubiiu/CodeTalker#67]
有在meshtalk的Issues里有看到您提问的问题，关于训练不收敛的问题，请问您的解决方式是什么呢？还请不吝赐教，谢谢！

**Comment by Doubiiu** [comment]
你好，我是通过调节超参，例如batch size，learning rate等使得模型训练可以收敛。具体的数值已经不是很记得了。

**Comment by AlongLove** [comment]
好的，非常感谢，它里面设置的segment_length在step1是32，step2是64，这个有调节过么？

**Comment by Doubiiu** [comment]
也有的，我好像大概试了8的倍数，大概16到48这样

**Comment by AlongLove** [comment]
好的，感谢赐教

**Comment by Doubiiu** [comment]
OK I will close this issue then. Please reopen it whenever you have any other questions.
