### ISSUE TITLE
Error when training stage2 

### ISSUE THREAD

**Issue by jinny960812** [Doubiiu/CodeTalker#7]
Hi, thanks for sharing your great work. 
When training stage 2 by executing `sh scripts/train.sh CodeTalker_s2 config/vocaset/stage2.yaml vocaset s2`, I get cuDNN error: CUDNN_STATUS_NOT_INITIALIZED. The error occurs when passing the audio into the audio encoder (wav2vec), at F.conv1d. 
I have followed the provided environment setting and the error still occurs. 
Can you help me solve the problem?

**Comment by Doubiiu** [comment]
Hi~ I am sorry that I didn't come across this issue before, so maybe I cannot provide useful information here. It is so weird as you can successfully run the code of stage 1. Not sure if it is related to wav2vec2? The possible solutions I think could be 1) Kill other running processes on your GPU and make sure there is enough free GPU memory. 2) Try other compatible pytorch & CUDA versions...

**Comment by jinny960812** [comment]
The problem was with setting the embedding dimension size!

**Comment by jeb0813** [comment]
Hi @jinny960812 , I also met this error, can you provide more info about how to slove it?
Thank you!
