### ISSUE TITLE
cal_metric.py error "FileNotFoundError: [Errno 2] No such file or directory: 'RUN/BIWI/CodeTalker_s2/result/npy/F2_e37_condition_F2.npy'"

### ISSUE THREAD

**Issue by bullgokman** [Doubiiu/CodeTalker#71]
In config/BIWI/stage2.yaml
train_subjects: F2 F3 F4 M3 M4 M5
test_subjects: F1 F5 F6 F7 F8 M1 M2 M6

And when i ran 'sh scripts/test.sh CodeTalker_s2 config/BIWI/stage2.yaml BIWI s2',
i got result files like'<test_subject>_e37~40_condition_<train_subject>.npy'.

For evaluating result files using cal_metric.py, result files have to be '<train_subject>_e37~40_condtiond_<train_subject>.npy'.

I think something wrong in test_pred.py.

**Comment by pepper725** [comment]
> In config/BIWI/stage2.yaml train_subjects: F2 F3 F4 M3 M4 M5 test_subjects: F1 F5 F6 F7 F8 M1 M2 M6
> 
> And when i ran 'sh scripts/test.sh CodeTalker_s2 config/BIWI/stage2.yaml BIWI s2', i got result files like'<test_subject>_e37~40_condition_<train_subject>.npy'.
> 
> For evaluating result files using cal_metric.py, result files have to be '<train_subject>_e37~40_condtiond_<train_subject>.npy'.
> 
> I think something wrong in test_pred.py.

How do you solve the problem，please?
